
# make CONFIG=Debug/Release

PROJ_SRCS     = sortL.c testSortL.c 
PROJ_INC_DIR  = ../DList
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      = testSortL.out
PROJ_MACROS   = XOR
PROJ_ADD_OBJS = DList.o
PROJ_LIBS     = 


include ../../Project.mak
