
# make CONFIG=Debug/Release

PROJ_SRCS     =MT_sort.c Test_MT_sort.c
PROJ_INC_DIR  =.
PROJ_OBJ_DIR  =../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  =../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      =Test_MT_sort.out
PROJ_MACROS   = _GNU_SOURCE _POSIX_SOURCE
PROJ_ADD_OBJS =
PROJ_LIBS     =pthread
PROJ_OTHERS   =

include ../../Project.mak
