
# make CONFIG=Debug/Release

PROJ_SRCS     = SList.c testSList.c
PROJ_INC_DIR  = ../pQueue ../DList ../sortL
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      = testSList.out
PROJ_MACROS   = 
PROJ_ADD_OBJS =  
PROJ_LIBS     = 


include ../../Project.mak
