
# make CONFIG=Debug/Release

PROJ_SRCS     =pingPong.c
PROJ_INC_DIR  =
PROJ_OBJ_DIR  =../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  =../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      =testPingPong.out
PROJ_MACROS   =
PROJ_ADD_OBJS =
PROJ_LIBS     =pthread
PROJ_OTHERS   =

include ../../Project.mak
