
# make CONFIG=Debug/Release

PROJ_SRCS     =recursion.c testRecursion.c
PROJ_INC_DIR  =../sList ../stack
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      =testRecursion.out
PROJ_MACROS   =
PROJ_ADD_OBJS =SList.o stack.o
PROJ_LIBS     =
PROJ_OTHERS   =../sList ../stack

include ../../Project.mak
