
# make CONFIG=Debug/Release

PROJ_SRCS     =
PROJ_INC_DIR  =
PROJ_OBJ_DIR  =../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  =../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      =
PROJ_MACROS   =
PROJ_ADD_OBJS =
PROJ_LIBS     =
PROJ_OTHERS   =

include ../../ProjectCPP.mak
