
# make CONFIG=Debug/Release

PROJ_SRCS     = DList.c testDList.c
PROJ_INC_DIR  = 
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      = testDList.out
PROJ_MACROS   = XOR
PROJ_ADD_OBJS =
PROJ_LIBS     = 


include ../../Project.mak
