
# make CONFIG=Debug/Release

PROJ_SRCS     = pQueueHeap.c testpQueueHeap.c
PROJ_INC_DIR  = ../heap ../vector
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      = testpQueueHeap.out
PROJ_MACROS   =
PROJ_ADD_OBJS = heap.o vector.o
PROJ_LIBS     =
PROJ_OTHERS   = ../heap

include ../../Project.mak
