
# make CONFIG=Debug/Release

PROJ_SRCS     = heap.c testHeap.c
PROJ_INC_DIR  = ../vector
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      = testHeap.out
PROJ_MACROS   =
PROJ_ADD_OBJS = vector.o
PROJ_LIBS     =
PROJ_OTHERS   = ../vector

include ../../Project.mak
