
# make CONFIG=Debug/Release

PROJ_SRCS     = pQueue.c testPQueue.c
PROJ_INC_DIR  = ../DList ../sortL
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      = testPQueue.out
PROJ_MACROS   = XOR
PROJ_ADD_OBJS = DList.o sortL.o
PROJ_LIBS     = 


include ../../Project.mak
