
# make CONFIG=Debug/Release

PROJ_SRCS     =hash.c testHash.c
PROJ_INC_DIR  =../AVL
PROJ_OBJ_DIR  =../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  =../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      =testHash.out
PROJ_MACROS   =_POSIX_SOURCE
PROJ_ADD_OBJS =AVL.o
PROJ_LIBS     =
PROJ_OTHERS   =

include ../../Project.mak
