
# make CONFIG=Debug/Release

PROJ_SRCS     = scheduler.c testSchduler.c task.c
PROJ_INC_DIR  = ../pQueueHeap/
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      = testSchduler.out
PROJ_MACROS   =
PROJ_ADD_OBJS = vector.o heap.o pQueueHeap.o
PROJ_LIBS     =
PROJ_OTHERS   = ../pQueueHeap ../heap ../vector


include ../../Project.mak
