
# make CONFIG=Debug/Release

PROJ_SRCS     =search.c testSearch.c
PROJ_INC_DIR  =
PROJ_OBJ_DIR  =../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  =../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      =testSearch.out
PROJ_MACROS   =
PROJ_ADD_OBJS =
PROJ_LIBS     =m
PROJ_OTHERS   =

include ../../Project.mak
