
# make CONFIG=Debug/Release

PROJ_SRCS     =vector.c testVector.c
PROJ_INC_DIR  =
PROJ_OBJ_DIR  =../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  =../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      =testVector.out
PROJ_MACROS   =
PROJ_ADD_OBJS =
PROJ_LIBS     =
PROJ_OTHERS   =

include ../../Project.mak
