
# make CONFIG=Debug/Release

PROJ_SRCS     =shape.cpp testShape.cpp
PROJ_INC_DIR  =
PROJ_OBJ_DIR  =../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  =../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      =testShape.out
PROJ_MACROS   =
PROJ_ADD_OBJS =
PROJ_LIBS     =glut_utils
PROJ_OTHERS   =

include ../../ProjectCPP.mak
