
# make CONFIG=Debug/Release

PROJ_SRCS     = scheduler.c testSchduler.c task.c
PROJ_INC_DIR  = ../pQueueHeap
PROJ_OBJ_DIR  = ../../../arch/linux64/obj/$(CONFIG)
PROJ_BIN_DIR  = ../../../arch/linux64/bin/$(CONFIG)
PROJ_OUT      = testSchduler.out
PROJ_MACROS   =
PROJ_ADD_OBJS = heap.o vector.o pQueueHeap.o
PROJ_LIBS     = ../pQueueHeap


include ../../Project.mak
